// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package auth_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type AuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	ExpirationTime       string   `protobuf:"bytes,3,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AuthResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *AuthResponse) GetExpirationTime() string {
	if m != nil {
		return m.ExpirationTime
	}
	return ""
}

type AuthorizationRequest struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationRequest) Reset()         { *m = AuthorizationRequest{} }
func (m *AuthorizationRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizationRequest) ProtoMessage()    {}
func (*AuthorizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{3}
}

func (m *AuthorizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationRequest.Unmarshal(m, b)
}
func (m *AuthorizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationRequest.Marshal(b, m, deterministic)
}
func (m *AuthorizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationRequest.Merge(m, src)
}
func (m *AuthorizationRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorizationRequest.Size(m)
}
func (m *AuthorizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationRequest proto.InternalMessageInfo

func (m *AuthorizationRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *AuthorizationRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *AuthorizationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthorizationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthorizationResponse struct {
	ResponseCode         int64    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationResponse) Reset()         { *m = AuthorizationResponse{} }
func (m *AuthorizationResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizationResponse) ProtoMessage()    {}
func (*AuthorizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{4}
}

func (m *AuthorizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationResponse.Unmarshal(m, b)
}
func (m *AuthorizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationResponse.Marshal(b, m, deterministic)
}
func (m *AuthorizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationResponse.Merge(m, src)
}
func (m *AuthorizationResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorizationResponse.Size(m)
}
func (m *AuthorizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationResponse proto.InternalMessageInfo

func (m *AuthorizationResponse) GetResponseCode() int64 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

type GetUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{5}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{6}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{7}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUserRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UpdateUserRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{8}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type DeleteUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{9}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserResponse struct {
	ResponseCode         int64    `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{10}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetResponseCode() int64 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

type TokenRefreshRequest struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRefreshRequest) Reset()         { *m = TokenRefreshRequest{} }
func (m *TokenRefreshRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRefreshRequest) ProtoMessage()    {}
func (*TokenRefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{11}
}

func (m *TokenRefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRefreshRequest.Unmarshal(m, b)
}
func (m *TokenRefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRefreshRequest.Marshal(b, m, deterministic)
}
func (m *TokenRefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRefreshRequest.Merge(m, src)
}
func (m *TokenRefreshRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRefreshRequest.Size(m)
}
func (m *TokenRefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRefreshRequest proto.InternalMessageInfo

func (m *TokenRefreshRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type TokenRefreshResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRefreshResponse) Reset()         { *m = TokenRefreshResponse{} }
func (m *TokenRefreshResponse) String() string { return proto.CompactTextString(m) }
func (*TokenRefreshResponse) ProtoMessage()    {}
func (*TokenRefreshResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{12}
}

func (m *TokenRefreshResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRefreshResponse.Unmarshal(m, b)
}
func (m *TokenRefreshResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRefreshResponse.Marshal(b, m, deterministic)
}
func (m *TokenRefreshResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRefreshResponse.Merge(m, src)
}
func (m *TokenRefreshResponse) XXX_Size() int {
	return xxx_messageInfo_TokenRefreshResponse.Size(m)
}
func (m *TokenRefreshResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRefreshResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRefreshResponse proto.InternalMessageInfo

func (m *TokenRefreshResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type VerifyEmailRequest struct {
	VerificationCode     string   `protobuf:"bytes,1,opt,name=verificationCode,proto3" json:"verificationCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailRequest) Reset()         { *m = VerifyEmailRequest{} }
func (m *VerifyEmailRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailRequest) ProtoMessage()    {}
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{13}
}

func (m *VerifyEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailRequest.Unmarshal(m, b)
}
func (m *VerifyEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailRequest.Marshal(b, m, deterministic)
}
func (m *VerifyEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailRequest.Merge(m, src)
}
func (m *VerifyEmailRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailRequest.Size(m)
}
func (m *VerifyEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailRequest proto.InternalMessageInfo

func (m *VerifyEmailRequest) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

type GenericResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{14}
}

func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (m *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(m, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func (m *GenericResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GenericResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*AuthRequest)(nil), "user.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "user.AuthResponse")
	proto.RegisterType((*AuthorizationRequest)(nil), "user.AuthorizationRequest")
	proto.RegisterType((*AuthorizationResponse)(nil), "user.AuthorizationResponse")
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "user.GetUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "user.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "user.DeleteUserResponse")
	proto.RegisterType((*TokenRefreshRequest)(nil), "user.TokenRefreshRequest")
	proto.RegisterType((*TokenRefreshResponse)(nil), "user.TokenRefreshResponse")
	proto.RegisterType((*VerifyEmailRequest)(nil), "user.VerifyEmailRequest")
	proto.RegisterType((*GenericResponse)(nil), "user.GenericResponse")
}

func init() {
	proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5)
}

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4b, 0x6f, 0xd3, 0x4c,
	0x14, 0x95, 0x93, 0xb4, 0xfd, 0x72, 0x13, 0xe5, 0x6b, 0x86, 0x14, 0x8c, 0x85, 0x20, 0x4c, 0x25,
	0x54, 0x21, 0x48, 0x44, 0x11, 0xa8, 0x08, 0x89, 0x57, 0x88, 0xd8, 0xb1, 0x30, 0x2d, 0x0b, 0x76,
	0xae, 0x7d, 0xd3, 0x8c, 0x48, 0xec, 0x30, 0x33, 0x2e, 0x0f, 0xb1, 0xe2, 0x0f, 0xb0, 0xe3, 0x47,
	0xf0, 0x2b, 0x91, 0xe7, 0x11, 0x3f, 0x92, 0x86, 0xb2, 0x9b, 0x7b, 0xe6, 0xce, 0x99, 0x3b, 0xe7,
	0x9e, 0x6b, 0xc3, 0xee, 0x82, 0x27, 0x32, 0x19, 0xa6, 0x02, 0xf9, 0x40, 0x2d, 0x49, 0x23, 0x5b,
	0xd3, 0x5f, 0x0e, 0x34, 0x4e, 0x04, 0x72, 0xd2, 0x81, 0x1a, 0x8b, 0x5c, 0xa7, 0xef, 0x1c, 0xd4,
	0xfd, 0x1a, 0x8b, 0xc8, 0x0d, 0x68, 0x4e, 0x18, 0x17, 0xf2, 0x6d, 0x30, 0x47, 0xb7, 0xd6, 0x77,
	0x0e, 0x9a, 0x7e, 0x0e, 0x10, 0x0f, 0xfe, 0x9b, 0x05, 0x66, 0xb3, 0xae, 0x36, 0x97, 0x31, 0xe9,
	0xc1, 0x16, 0xce, 0x03, 0x36, 0x73, 0x1b, 0x6a, 0x43, 0x07, 0xd9, 0x89, 0x45, 0x20, 0xc4, 0xe7,
	0x84, 0x47, 0xee, 0x96, 0x3e, 0x61, 0x63, 0x42, 0xa0, 0xc1, 0x93, 0x19, 0xba, 0xdb, 0x0a, 0x57,
	0x6b, 0x3a, 0x86, 0xd6, 0xcb, 0x54, 0x4e, 0x7d, 0xfc, 0x94, 0xa2, 0x90, 0xd9, 0xf1, 0xac, 0xde,
	0x38, 0xbb, 0xd0, 0xd1, 0xc7, 0x6d, 0x5c, 0xa2, 0xae, 0x95, 0xa9, 0xe9, 0x77, 0x68, 0x6b, 0x1a,
	0xb1, 0x48, 0x62, 0x81, 0xa4, 0x0f, 0xad, 0x20, 0x0c, 0x51, 0x88, 0xe3, 0xe4, 0x23, 0xc6, 0x86,
	0xaa, 0x08, 0x11, 0x0a, 0x6d, 0x8e, 0x13, 0x8e, 0x62, 0xaa, 0x53, 0x34, 0x63, 0x09, 0x23, 0x77,
	0xa0, 0x83, 0x5f, 0x16, 0x8c, 0x07, 0x92, 0x25, 0xf1, 0x31, 0x5b, 0x8a, 0x50, 0x41, 0xe9, 0x0f,
	0x07, 0x7a, 0xd9, 0xf5, 0x09, 0x67, 0xdf, 0x14, 0x6a, 0x9f, 0x63, 0xd5, 0x2d, 0xbc, 0x27, 0x07,
	0xac, 0xba, 0x71, 0x2e, 0xfd, 0x32, 0xce, 0xd5, 0xad, 0x5f, 0xa4, 0x6e, 0xa3, 0x22, 0xc1, 0x53,
	0xd8, 0xab, 0xd4, 0x60, 0xb4, 0x50, 0x2f, 0xd5, 0xeb, 0x51, 0x12, 0xa1, 0x69, 0x7e, 0x09, 0xa3,
	0x7d, 0xe8, 0xbc, 0x41, 0x99, 0x39, 0xc4, 0x96, 0x5e, 0x31, 0x0a, 0x7d, 0x00, 0xff, 0x2f, 0x33,
	0x0c, 0xf1, 0x4d, 0x50, 0xe6, 0x52, 0x49, 0xad, 0x43, 0x18, 0x28, 0xd7, 0xa9, 0x0c, 0x6d, 0xba,
	0x9f, 0x0e, 0x74, 0x4f, 0x16, 0x51, 0x20, 0x71, 0x03, 0x71, 0x59, 0xa3, 0xda, 0x26, 0x8d, 0xea,
	0x17, 0x69, 0x74, 0x59, 0x07, 0xd2, 0x7b, 0x40, 0x8a, 0x05, 0x99, 0x77, 0x5c, 0x85, 0x6d, 0x21,
	0x03, 0x99, 0x0a, 0xd3, 0x22, 0x13, 0xd1, 0x7d, 0xe8, 0xbe, 0xc6, 0x19, 0x6e, 0x2c, 0x9f, 0x1e,
	0x01, 0x29, 0x26, 0xfd, 0x83, 0xe6, 0x4f, 0xe0, 0x8a, 0xb2, 0x99, 0xaf, 0x2d, 0x67, 0x2f, 0xa8,
	0x1a, 0xd3, 0x59, 0x35, 0x26, 0x3d, 0x82, 0x5e, 0xf9, 0xe8, 0x65, 0x6d, 0x4f, 0x5f, 0x00, 0x79,
	0x8f, 0x9c, 0x4d, 0xbe, 0x8e, 0x33, 0xb1, 0xec, 0x9d, 0x77, 0x61, 0xf7, 0x3c, 0x43, 0x59, 0xa8,
	0xac, 0xb3, 0x2c, 0xb9, 0xe9, 0xaf, 0xe0, 0x74, 0x94, 0x19, 0x21, 0x46, 0xce, 0xc2, 0xbf, 0x09,
	0x48, 0x5c, 0xd8, 0x99, 0xa3, 0x10, 0xc1, 0x99, 0x6d, 0xac, 0x0d, 0x0f, 0x7f, 0xd7, 0xf5, 0xdc,
	0xbf, 0x43, 0x7e, 0xce, 0x42, 0x24, 0x8f, 0xf4, 0xfc, 0x62, 0x2c, 0xb3, 0xab, 0x90, 0x74, 0xb5,
	0x99, 0x0a, 0x9f, 0x06, 0x8f, 0x14, 0x21, 0x73, 0xf1, 0x18, 0xda, 0x7e, 0x71, 0x60, 0xaf, 0xeb,
	0x9c, 0x35, 0xb2, 0x7a, 0xde, 0xba, 0x2d, 0x43, 0xb3, 0x0f, 0x4d, 0x3b, 0x3a, 0x48, 0x0a, 0x3e,
	0xf6, 0x0a, 0x6b, 0xf2, 0x18, 0x76, 0xcc, 0x00, 0x90, 0x9e, 0x86, 0xcb, 0x13, 0xe3, 0xed, 0x55,
	0x50, 0x43, 0xfe, 0x1c, 0x20, 0xf7, 0x1c, 0xb9, 0x66, 0x18, 0xab, 0x63, 0xe1, 0xb9, 0xab, 0x1b,
	0x39, 0x41, 0xee, 0x30, 0x4b, 0xb0, 0x62, 0x4c, 0x4b, 0xb0, 0xc6, 0x8c, 0xcf, 0xa0, 0x55, 0xe8,
	0x39, 0x31, 0x89, 0xab, 0x36, 0xc8, 0x5f, 0x50, 0x6a, 0xef, 0xab, 0xdb, 0x1f, 0x6e, 0x9d, 0x31,
	0x39, 0x4d, 0x4f, 0x07, 0x61, 0x32, 0x1f, 0x8e, 0xa6, 0x01, 0x8b, 0x31, 0x1a, 0x06, 0xa9, 0x9c,
	0xde, 0x17, 0xba, 0x7f, 0xa7, 0xdb, 0xea, 0x67, 0xf3, 0xf0, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x12, 0xaf, 0x9e, 0x06, 0x80, 0x06, 0x00, 0x00,
}
